import { addDays, atHour } from "./dates";
import type { DeskState } from "./types";

export function emptyDesk(): DeskState {
  return {
    version: 1,
    hydrated: false,
    asOf: 0,
    priorities: [],
    people: [],
    meetings: [],
    decisions: [],
    followUps: [],
    inbox: [],
    lastReply: "",
  };
}

export function createSeedState(now = Date.now()): DeskState {
  const today = atHour(now, 9);
  return {
    version: 1,
    hydrated: true,
    asOf: now,
    lastReply: "",
    people: [
      {
        id: "ppl_elena",
        name: "Elena Voss",
        role: "General counsel",
        organization: "Hillman desk",
        email: "elena@example.com",
        relationship: "counsel",
        warmth: "close",
        lastContactAt: addDays(now, -1),
        nextAction: "Send the Aurora pathway memo before the 10:00.",
        notes: "Prefers written options with a recommended path, not a raw dump.",
      },
      {
        id: "ppl_marcus",
        name: "Marcus Chen",
        role: "Managing partner",
        organization: "Northwater",
        email: "marcus@example.com",
        relationship: "investor",
        warmth: "warm",
        lastContactAt: addDays(now, -4),
        nextAction: "Confirm whether they want a second look at the 510(k) file.",
        notes: "Cares about regulatory timeline risk more than valuation theater.",
      },
      {
        id: "ppl_priya",
        name: "Priya Nandakumar",
        role: "CEO",
        organization: "Aurora Bio",
        email: "priya@example.com",
        relationship: "operator",
        warmth: "close",
        lastContactAt: addDays(now, -2),
        nextAction: "Ask for the residual-risk table before diligence closes.",
        notes: "Direct. Will not pad a weak data room.",
      },
      {
        id: "ppl_joan",
        name: "Joan Hale",
        role: "Reviewer",
        organization: "FDA CDRH",
        email: "",
        relationship: "regulator",
        warmth: "warm",
        lastContactAt: addDays(now, -18),
        nextAction: "Do not freelance a contact. Route through counsel.",
        notes: "Public-facing only. Treat as institutional, not personal.",
      },
      {
        id: "ppl_samir",
        name: "Samir Adeyemi",
        role: "Scholar",
        organization: "Andrew Hillman Scholarship",
        email: "samir@example.com",
        relationship: "scholar",
        warmth: "warm",
        lastContactAt: addDays(now, -36),
        nextAction: "Check in on the fall term and the biotech lab placement.",
        notes: "Quiet. Writes well. Last note mentioned a stalled mentor match.",
      },
    ],
    priorities: [
      {
        id: "pri_aurora",
        title: "Close Aurora diligence or walk",
        why: "The pathway choice changes the hold period and the residual risk.",
        rank: 1,
        status: "active",
        dueAt: addDays(now, 5),
      },
      {
        id: "pri_scholarship",
        title: "Lock the scholarship selection calendar",
        why: "Awards slip if reviewers do not have a hard date.",
        rank: 2,
        status: "active",
        dueAt: addDays(now, 12),
      },
      {
        id: "pri_positions",
        title: "Publish the public positions note on pathway selection",
        why: "The record should say what we believe before the next inbound.",
        rank: 3,
        status: "active",
        dueAt: addDays(now, 9),
      },
      {
        id: "pri_family",
        title: "Quarterly family-office cash and commitment review",
        why: "Stewardship is the job. The operating companies are the means.",
        rank: 4,
        status: "parked",
        dueAt: addDays(now, 20),
      },
    ],
    meetings: [
      {
        id: "mtg_counsel",
        title: "Aurora pathway with counsel",
        startsAt: atHour(today, 10),
        endsAt: atHour(today, 10, 45),
        attendeeIds: ["ppl_elena"],
        purpose: "Choose 510(k) vs De Novo framing for the memo.",
        prep: "Read Elena's draft options. Bring the residual-risk table if Priya sent it.",
        outcome: "",
        status: "upcoming",
      },
      {
        id: "mtg_priya",
        title: "Diligence working session — Aurora",
        startsAt: atHour(today, 15),
        endsAt: atHour(today, 16),
        attendeeIds: ["ppl_priya", "ppl_elena"],
        purpose: "Pressure-test the data room against the pathway memo.",
        prep: "",
        outcome: "",
        status: "upcoming",
      },
      {
        id: "mtg_marcus",
        title: "Northwater update",
        startsAt: atHour(addDays(today, 1), 11),
        endsAt: atHour(addDays(today, 1), 11, 30),
        attendeeIds: ["ppl_marcus"],
        purpose: "Give them a clean yes/no on a second look.",
        prep: "One page: what we know, what we do not, what we will not pretend.",
        outcome: "",
        status: "upcoming",
      },
    ],
    decisions: [
      {
        id: "dec_pathway",
        question: "Do we treat Aurora as a 510(k) or a De Novo from day one?",
        context:
          "A 510(k) is faster if the predicate holds. A De Novo is honest if it does not. Counsel wants a written choice before the afternoon session.",
        status: "pending",
        decision: "",
        createdAt: addDays(now, -11),
        decidedAt: null,
      },
      {
        id: "dec_second_look",
        question: "Does Northwater get a second look at the Aurora file?",
        context: "Marcus asked. Sharing too early trains the wrong habit.",
        status: "pending",
        decision: "",
        createdAt: addDays(now, -3),
        decidedAt: null,
      },
      {
        id: "dec_grant",
        question: "Do we keep the biotech grant as a separate award this year?",
        context: "Split awards are clearer. Combined awards are cheaper to administer.",
        status: "decided",
        decision: "Keep them separate. Clarity over convenience.",
        createdAt: addDays(now, -20),
        decidedAt: addDays(now, -6),
      },
    ],
    followUps: [
      {
        id: "fu_risk",
        title: "Get the residual-risk table from Priya",
        personId: "ppl_priya",
        dueAt: atHour(addDays(now, -1), 17),
        status: "open",
        source: "Last Aurora call",
        createdAt: addDays(now, -4),
      },
      {
        id: "fu_memo",
        title: "Send Elena the annotated pathway options",
        personId: "ppl_elena",
        dueAt: atHour(now, 9, 30),
        status: "open",
        source: "Counsel prep",
        createdAt: addDays(now, -2),
      },
      {
        id: "fu_samir",
        title: "Write Samir about the mentor match",
        personId: "ppl_samir",
        dueAt: atHour(addDays(now, 2), 17),
        status: "open",
        source: "Scholarship desk",
        createdAt: addDays(now, -8),
      },
      {
        id: "fu_marcus",
        title: "Decide the Northwater second-look answer",
        personId: "ppl_marcus",
        dueAt: atHour(addDays(now, 1), 9),
        status: "open",
        source: "Investor inbound",
        createdAt: addDays(now, -3),
      },
    ],
    inbox: [
      {
        id: "inb_intro",
        title: "Inbound: intro to a diagnostics operator",
        body: "Warm intro via Marcus. No materials yet. Do not take a meeting until there is a one-pager.",
        createdAt: addDays(now, -1),
        status: "open",
      },
    ],
  };
}
